package com.hasan.nisabwallet.data.model

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.util.Date

/**
 * Mirrors the web app's transaction structure.
 *
 * type: "Income" | "Expense"
 * Special flags:
 *   isRiba      → appears in Riba Tracker (category = "Interest / Riba")
 *   isSadaqah   → recorded to purify a riba transaction
 *   ribaRefId   → links a sadaqah expense back to its riba income
 */
data class Transaction(
    @DocumentId
    val id: String           = "",
    val transactionId: String = "",
    val type: String         = "Expense",   // "Income" | "Expense"
    val amount: Double       = 0.0,
    val accountId: String    = "",
    val accountName: String  = "",          // denormalised for display
    val categoryId: String   = "",
    val categoryName: String = "",          // denormalised
    val categoryColor: String = "#6B7280",  // denormalised
    val description: String  = "",
    val date: String         = "",          // ISO yyyy-MM-dd
    val isRiba: Boolean      = false,
    val isSadaqah: Boolean   = false,
    val ribaRefId: String    = "",
    val sadaqahDone: Boolean  = false,
    val sadaqahAmount: Double = 0.0,
    val sadaqahDate: String   = "",
    val recurringId: String   = "",         // set if generated by a recurring rule
    @ServerTimestamp
    val createdAt: Date?     = null
) {
    val isIncome: Boolean  get() = type == "Income"
    val isExpense: Boolean get() = type == "Expense"

    /** Amount with sign — positive for income, negative for expense */
    val signedAmount: Double get() = if (isIncome) amount else -amount
}
